zotero-chinese/zotero-plugins

- docs/charts.html
- docs/index.html
- package.json
- src/charts.ts
- src/index.ts
> 添加标题、图标、加载动画

- docs/README.md
- docs/index.html
仅根据插件名称，简介，作者进行搜索，功能类似Ctrl + F 浏览器搜索，无高级的模糊搜索功能
> 添加简单的插件搜索功能

- src/charts.ts
- stars/day -> stars/week
- total downloads -> downloads/day
> update activities chart

- docs/index.html
> 搜索框支持使用`或`条件

- .github/workflows/charts.yml
- .github/workflows/plugins-info.yml
- src/index.ts
建了小号，开 PAT ，速率限制应从 1000 次/小时 提高到 5000 次/小时。
> 修改GitHub PAT以缓解API rate limit

- docs/README.md
> 增加插件与Zotero兼容性和安装插件文档的提示

- src/plugins.ts
Add new version for Zoplicate, which will support Zotero 6
> Add new version of Zoplicate

- src/plugins.ts
> Add MarkDBConnect for Zotero 7

- src/plugins.ts
duplicate plugin:
https://github.com/zotero-chinese/zotero-plugins/blob/7b26842ca1d3538b147ee9b1fe75196dd5bdbaef/src/plugins.ts#L423
https://github.com/zotero-chinese/zotero-plugins/blob/7b26842ca1d3538b147ee9b1fe75196dd5bdbaef/src/plugins.ts#L501
> remove duplicate plugin

- src/renderMarkdown.ts
fix https://github.com/zotero-chinese/zotero-plugins/issues/64
> Fix rendering issues in Markdown tables caused by `|` in fields.

- src/get_plugins_info.ts
- src/plugins.ts
距离这几个字段变更已经过去一段时间了，应该已经完成了更新，可以选一个合适的时间合并此 PR。为确保兼容性也可以再等一等。
Ref: 
- #61 
- #62
- #57 
- https://github.com/zotero-chinese/zotero-plugins/pull/54#issuecomment-1854943840
- #55
> fix: remove deprecated field

- src/plugins.ts
> Add Zotero 7 Citation Counts Manager Enhaned

- package.json
- pnpm-lock.yaml
- src/get-plugins-info.ts
- src/index.ts
- src/plugins.ts
resolve: https://github.com/zotero-chinese/zotero-plugins/pull/80#issuecomment-1952501863
> 移除ZotIF，修改ZotMoov，允许处理JSONC

- src/plugins.ts
resolve: https://github.com/zotero-chinese/zotero-plugins/pull/80#discussion_r1498626866
> Add Zotero 7 for Zotxt

- src/plugins.ts
增加zzlb0224/zotero-annotation-manage
```
{
name: "Zotero Annotation Manage",
repo: "zzlb0224/zotero-annotation-manage",
releases: [
{
targetZoteroVersion: "7",
tagName: "latest",
},
],
},
```
> 增加zzlb0224/zotero-annotation-manage

- src/charts.ts
related: https://github.com/zotero-chinese/website/pull/52
> Remove title cell from charts data

- src/plugins.ts
add Zotero-tts plugin for zotero7
tags若定的不符合请更改
> Add ImperialSquid/zotero-zotts

- src/plugins.ts
fix: Update release to the latest for Jasminum.
> Update Jasminum for Z7

- src/plugins.ts
update Jasminum v0.3.1 for Zotero 6 manually
> Update Jasminum for Zotero 6

- src/plugins.ts
> Translate: restore to latest

- src/plugins.ts
> Add plugins

- src/handler/plugins-data.ts
- src/plugins.ts
- src/types.ts
- src/utils/fs.ts
closes: #123 
poly 的几个插件已有一段时间仅在 Gitee 更新，商店脚本常抓取到旧版本插件，对一些用户造成了困扰。
这个 PR 中，修改了一部分数据以支持从 GitHub 以外下载 XPI 文件。
以 style 为例，得到的 json 将会是如下：
```diff
[
{
"repo": "MuiseDestiny/ZoteroStyle",
"releases": [
{
"targetZoteroVersion": "7",
--      "tagName": "latest",
++      "tagName": "custom",
++      "customLink": "https://gitee.com/MuiseDestiny/plugins/raw/master/zotero-style.xpi",
"releaseDate": "2025-02-28T15:45:30.000Z",
--      "assetId": 123456,       // 原来是 GitHub release asset 的 id
++      "assetId": "MuiseDestiny-ZoteroStyle-7",
"downloadCount": 0,      // 无法获取下载了，全部记为 0
"xpiDownloadUrl": {      // 全部为其自行托管的下载地址
"gitee": "https://gitee.com/MuiseDestiny/plugins/raw/master/zotero-style.xpi",
"github": "https://gitee.com/MuiseDestiny/plugins/raw/master/zotero-style.xpi",
"ghProxy": …
```
> Fix MuiseDestiny's plugin which release in gitee

- src/plugins.ts
> Add know-ur-zotero

- src/handler/plugins-data.ts
visit ghproxy.com report 301 Moved Permanently, replace it to gh-proxy.com
> replace ghproxy link 

- src/plugins.ts
> add retorquere/zotero-folder-import

- src/deprecated.ts
- src/plugins.ts
Hi, I recently updated KeepZotero to support Zotero 7.
I move it to src/plugin.ts with the corresponding tag for Zotero 6 and 7.
Please let me know if I miss anything.
> update KeepZotero with Zotero 7 support

- src/plugins.ts
坚果云官方对于 zotero 的单点登录的插件，可以快速设置 webdav
> feat: add nutstore/zotero-plugin-nutstore-sso

- src/plugins.ts
For setting the PDF view to horizontal Scrolling and zooming to the page height as defaults. 
The needs of many people on the forum:
1. https://forums.zotero.org/discussion/108902/default-pdf-view-settings
2. https://forums.zotero.org/discussion/comment/409604
> Add qiwei-ma/zotero-pdf-setHorizontal

- src/plugins.ts
Add a plugin: Its primary function is to assist users in reading research papers by generating relevant summaries based on the title and abstract of the paper.​
> feat: add new-plugin zotero-skr to plugins list

- src/plugins.ts
Update jasminum v0.3.2 for Zotero 6
> update jasminum for  Zotero 6 : v0.3.2

- src/plugins.ts
> Add suppr zotero plugin for PDF translating

- src/plugins.ts
研学港 Researchopia - 开放的学术交流平台。支持对文献的评分和讨论，后续还将开发更多功能，敬请期待！
> Add new repository “Researchopia” with releases and tags
